package com.preventiva.backend.enums;

public enum CampoDestino {

    // Cirugía
    CIRUGIA_HC,
    CIRUGIA_SEXO,
    CIRUGIA_EDAD,
    CIRUGIA_FECHA_INGRESO,
    CIRUGIA_FECHA_ALTA,
    CIRUGIA_FECHA_CIRUGIA,
    CIRUGIA_SERVICIO,
    CIRUGIA_PROCEDIMIENTO,
    CIRUGIA_CIE10,
    CIRUGIA_DURACION_MINUTOS,
    CIRUGIA_URGENTE,
    CIRUGIA_ASA,
    CIRUGIA_GRADO_CONTAMINACION_INICIAL,
    CIRUGIA_GRADO_CONTAMINACION_FINAL,
    CIRUGIA_ABORDAJE_QUIRURGICO,
    CIRUGIA_MULTIRRESISTENTES,

    // Profilaxis
    PROFILAXIS_INDICACION,
    PROFILAXIS_ADMINISTRACION,
    PROFILAXIS_DRAGO,
    PROFILAXIS_ADECUACION,
    PROFILAXIS_MOTIVO_INADECUACION,
    PROFILAXIS_VALIDACION_DOSIS_ADICIONALES,

    // ILQ
    ILQ_TIENE,
    ILQ_FECHA,
    ILQ_FECHA_FIN_VIGILANCIA,
    ILQ_LOCALIZACION,
    ILQ_REINGRESO,
    ILQ_FECHA_REINGRESO,

    // Microbiología
    MICRO_CULTIVO_ILQ,
    MICRO_TIPO_MUESTRA,
    MICRO_RESULTADO_CULTIVO,
    MICRO_MICROORGANISMO,
    MICRO_RESISTENCIA,
    MICRO_OTRA_RESISTENCIA,

    // Seguimiento postoperatorio
    SEGUIMIENTO_EDAD_MESES_MENOR_2,
    SEGUIMIENTO_EXITUS_POST_CIRUGIA,
    SEGUIMIENTO_MOTIVO_ALTA,
    SEGUIMIENTO_COMENTARIOS,

    // Medidas preventivas
    PREVENTIVA_MONITORIZACION_TEMPERATURA,
    PREVENTIVA_GLUCEMIA_INTRAOPERATORIA,
    PREVENTIVA_ELIMINACION_VELLO,
    PREVENTIVA_MOMENTO_ELIMINACION_VELLO,
    PREVENTIVA_TECNICA_ELIMINACION_VELLO,
    PREVENTIVA_OTRA_TECNICA_ELIMINACION_VELLO,
    PREVENTIVA_ANTISEPSIA_PIEL,

    // Microbiología ampliada
    MICRO_OTRA_MUESTRA,

    // Campo ignorado
    IGNORAR,
}