package com.preventiva.backend.enums;

public enum TipoErrorImportacion {
    COLUMNA_OBLIGATORIA_FALTANTE,
    VALOR_OBLIGATORIO_VACIO,
    FORMATO_FECHA_INVALIDO,
    FORMATO_NUMERO_INVALIDO,
    FORMATO_BOOLEANO_INVALIDO,
    VALOR_NO_RECONOCIDO,
    FILA_VACIA,
    COLUMNA_NO_RECONOCIDA,
    SIN_FILAS_CLINICAS,
    ERROR_DESCONOCIDO
}