package com.preventiva.backend.enums;

public enum TipoEventoImportacionTrabajo {
    COPIA_CREADA,
    CELDA_CORREGIDA,
    CORRECCION_CELDA_DESHECHA,
    CORRECCIONES_FILA_DESHECHAS,
    TODAS_CORRECCIONES_DESHECHAS,
    FILA_EXCLUIDA,
    FILA_INCLUIDA,
    FILAS_SIMILARES_EXCLUIDAS,
    TODAS_EXCLUSIONES_DESHECHAS,
    COPIA_RESTAURADA_ORIGINAL,
    COLUMNA_RELLENADA,
    COLUMNA_NORMALIZADA,
    REVALIDACION_EJECUTADA,
    IMPORTACION_REALIZADA,
    DATASET_ACTIVADO,
    BORRADOR_DESCARTADO,
    COPIA_DESCARTADA
}
